config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'


  resources :projects

  resources :tickets do
    resources :comments, only: [:create, :edit, :update]
  end

  resources :tags

  resources :users, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :creator, class_name: 'User'

  validates :body, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }

  has_many :tickets, dependent: :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2 }

  has_many :ticket_tags, dependent: :destroy
  has_many :tickets, through: :ticket_tags
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  OPTIONS = ['New', 'Blocked', 'In progress', 'Fixed']

  validates :name, :status, presence: true
  validates :status, inclusion: { in: %w(new blocked in_progress fixed)}

  belongs_to :project, validate: true
  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true
  has_many :ticket_tags, dependent: :destroy
  has_many :tags, through: :ticket_tags
  has_many :comments, dependent: :destroy
end

app/models/ticket_tag.rb
class TicketTag < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, on: :create, length: { minimum: 5 }

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate
  
  def create
    @comment = Comment.new(comment_body)
    @comment.creator = current_user
    @ticket = Ticket.find(params[:ticket_id])
    @comment.ticket = @ticket

    unless @comment.save
      render :edit and return
    end

    if params[:comment][:ticket_status].present?
      @ticket = Ticket.find(params[:ticket_id])
      @ticket.status = params[:comment][:ticket_status]
      @ticket.save
    end

    flash[:success] = "Comment created."
    redirect_to ticket_path(params[:ticket_id])
  end

  def edit
    @comment = Comment.find(params[:id])
    validate_user
    @ticket = Ticket.find(params[:ticket_id])
  end

  def update
    @comment = Comment.find(params[:id])
    validate_user
    @comment.body = params[:comment][:body]
    unless @comment.save
      render :edit
    end

    if params[:comment][:ticket_status].present?
      @ticket = Ticket.find(params[:ticket_id])
      @ticket.status = params[:comment][:ticket_status]
      @ticket.save
    end

    flash[:success] = "Comment updated."
    redirect_to ticket_path(params[:ticket_id])
  end

  private

  def authenticate
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to ticket_path(params[:ticket_id])
    end
  end

  def validate_user
    if current_user.id != @comment.creator.id
      flash[:error] = "You can only edit your own comments."
      redirect_to ticket_path(params[:ticket_id])
    end
  end

  def comment_body
    params.require(:comment).permit(:body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  def index
    @projects = Project.includes(:tickets)
  end

  def show
    @tickets = @project.tickets 
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Project was created successfully."
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      flash[:success] = "Project was updated successfully."
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private 

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def authenticate
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to root_path
    else
      flash[:error] = "There is something wrong with your email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: [:edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  def index
    tags_in_order_with_count
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "Tag successfully created."
      redirect_to tags_path
    else 
      render :new
    end
  end

  def edit; end

  def update
    if @tag.update(tag_params)
      flash[:success] = "Tag successfully updated."
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end

  def find_tag
    @tag = Tag.find(params[:id])
  end

  private

  def tags_in_order_with_count
    @tags = Tag.left_outer_joins(:ticket_tags).select("tags.*, COUNT(ticket_tags.id)").group("tags.id").order("LOWER(tags.name) ASC")
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

  def authenticate
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to tags_path
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_ticket, only: [:show, :update, :edit, :destroy]
  before_action :authenticate, except: [:index, :show]

  def index
    @tickets = Ticket.all

    if params[:tag_id].present?
      @tickets = Tag.find(params[:tag_id]).tickets
      @tag = params[:tag_id]
    end

    if params[:ticket]
      @tickets = @tickets.where(filter_params.reject { |k,v| v.blank? })
      @project_id = filter_params[:project_id]
      @status = filter_params[:status]
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.creator = @current_user
    
    if @ticket.save
      flash[:success] = "Ticket created successfully."
      redirect_to tickets_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new 
  end

  def edit; end

  def update
    if @ticket.update(ticket_params)
      flash[:success] = "Ticket updated successfully."
      redirect_to tickets_path
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def filter_params
    params.require(:ticket).permit(:project_id, :status)
  end

  def ticket_params
    params.require(:ticket).permit(:project_id, :status, :name, :body, :assignee_id, :tag_ids => [])
  end
  
  def find_ticket
    @ticket = Ticket.find(params[:id])
  end

  def authenticate
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to tickets_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You are registered."
      redirect_to root_path
    else
      render :new      
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: 'Comment'%>

  <%= render 'shared/errors', obj: @comment%>

  <%= render 'shared/comment_form' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, class:'form-control', rows: '9' %>
  </div>

  <%= f.submit(@project.new_record? ? 'Create' : 'Update' , class: 'btn btn-primary btn-lg')%>
<% end %>

app/views/projects/edit.html.erb
<%= render 'shared/nav' %>

<div class="container mt-lg-3">
  <%= render 'shared/header', title: 'Editing Project'%>

  <%= render 'shared/errors', obj: @project %>

  <%= render 'form' %>

  <%= link_to 'Show', project_path(@project) %>
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: 'Projects' %>

  <% if flash[:error].present? %>
    <p class="alert alert-danger"><%= flash[:error] %></p>
  <% end %>
  <% if flash[:success].present? %>
    <p class="alert alert-success"><%= flash[:success] %></p>
  <% end %>
  <% if flash[:notice].present? %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
  <% end %>
  
  <% if @projects.any? %>
    <table class="table w-100 table-hover table-sm">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Open Tickets</th>
          <th>Total Tickets</th>
          <% if logged_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>

        <% @projects.each do |project| %>
          <tr>
            <td>
              <h3><%= link_to project.name, project_path(project.id)%></h3>
              <p><%= project.description %><p>
            </td>
            <td><%= project.tickets.select { |ticket| ticket.status != 'fixed' }.size %></td>
            <td><%= project.tickets.size %></td>
            <% if logged_in? %>
              <td>
                <%= link_to 'Edit', edit_project_path(project)%>
                <%= link_to 'Delete', project_path(project), method: :delete, data: {confirm: "Are you sure?" } %>
              </td>
            <% end %>
          </tr>
        <% end%>
    </table>
  <% else %>
    <p class="lead">No projects yet.</p>
  <% end %>

  <button class='btn btn-outline-primary'><%= link_to 'New Project', new_project_path, class: 'boring' %></button>
</div>

app/views/projects/new.html.erb
<%= render 'shared/nav' %>

<div class="container mt-lg-3">
  <%= render 'shared/header', title: 'New Project' %>

  <%= render 'shared/errors', obj: @project %>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<%= render 'shared/nav'%>

<div class="container mt-lg-3">
  <%= render 'shared/header', title: @project.name %>
  <p class="lead"><%= @project.description %></p>

  <ul>
    <%= link_to 'Edit', edit_project_path(@project) %>
    <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?" } %>
  </ul>
    

  <%= render 'shared/ticket_list'%>

</div>

app/views/shared/_comment_form.html.erb
<%= form_for [@ticket, @comment], class: 'mt-lg-5' do |f| %>
      <div class="form-group">
        <%= f.label :body, 'Add a comment' %>
        <%= f.text_area :body, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= label_tag 'comment[ticket_status]', 'Update ticket status' %>
        <%= select_tag 'comment[ticket_status]',
                        options_for_select(Ticket::OPTIONS.map { |option| [option, option.downcase.split.join('_')]}), 
                        include_blank: 'Do not change',
                        class: 'form-control' %>
      </div>

      <%= f.submit(@comment.new_record? ? 'Create Comment' : 'Update Comment', class: 'btn btn-primary btn-lg')%>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
  <h1 class="display-4"><%= title %></h1>

app/views/shared/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
  
  <strong><%= link_to 'Ticketing', root_path, class: "navbar-brand" %></strong>
  
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to 'Projects', projects_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Tickets', tickets_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Tags', tags_path, class: "nav-link" %>
    </li>
  </ul>

  <ul class="navbar-nav ">
    <% unless logged_in? %>
      <li class="nav-item ">
        <button class="btn btn-lg"><%= link_to 'Login', login_path, class: "nav-link" %></button>
      </li>
      <li class="nav-item ">
        <button class="btn btn-lg"><%= link_to 'Signup', register_path, class: "nav-link" %></button>
      </li>
    <% else %>
      <li class="nav-item ">
        <span>Logged in as <%= current_user.name %></span>
        <button class="btn btn-lg"><%= link_to 'Logout', logout_path, class: "nav-link" %></button>
      </li>
    <% end %>
  <ul>
</nav>

app/views/shared/_ticket_list.html.erb
  <table class="table w-100 table-hover table-sm mt-lg-3">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Assignee</th>
        <th>Status</th>
        <th>Tags</th>
        <% if logged_in? %>
          <th></th>
        <% end %>
      </tr>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= link_to ticket.name, ticket_path(ticket.id) %></td>
          <td><%= ticket.assignee && ticket.assignee.name%></td>
          <td><%= ticket.status.capitalize.split('_').join(' ') %></td>
          <td><%= ticket.tags.to_a.map {|tag| tag.name }.join(', ') %></td>
          <% if logged_in? %>
            <td>
              <ul>
                <%= link_to 'Edit', edit_ticket_path(ticket.id) %>
                <%= link_to 'Destroy', ticket_path(ticket.id), method: :delete, data: {confirm: "Are you sure?"} %>
              </ul>
            </td>
          <% end %>
        </tr>
      <% end %>
    </thead>
  </table>

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit(@tag.new_record? ? 'Create Tag' : 'Update Tag', class: 'btn btn-primary btn-lg')%>
  <%= link_to 'Back', tags_path, class: 'ml-lg-3' %>
<% end %>

app/views/tags/edit.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: 'Editing Tag'%>

  <%= render 'shared/errors', obj: @tag %>

  <%= render 'form' %>
</div>

app/views/tags/index.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: 'Tags' %>

  <% if flash[:error].present? %>
    <p class="alert alert-danger"><%= flash[:error] %></p>
  <% end %>
  <% if flash[:success].present? %>
    <p class="alert alert-success"><%= flash[:success] %></p>
  <% end %>
  
  <% if @tags.any? %>
    <table class="table w-100 table-hover table-sm">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Tickets</th>
          <% if logged_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td><%= link_to tag.tickets.count, "#{tickets_path}?tag_id=#{tag.id}" %></td>
          <% if logged_in? %>
            <td>
              <%= link_to 'Edit', edit_tag_path(tag.id) %>
              or
              <%= link_to 'Destroy', tag_path(tag.id), method: :delete, data: { confirm: "Are you sure?" }%>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p class="lead">No tags yet.</p>
  <% end %>

  <button class='btn btn-outline-primary'><%= link_to 'New Tag', new_tag_path, class: 'boring' %></button>

</div>

app/views/tags/new.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: 'New Tag' %>

  <%= render 'shared/errors', obj: @tag %>

  <%= render 'form'%>
<div>

app/views/tickets/_form.html.erb
<%= form_for @ticket do |f| %>
  <div class="form-group mt-lg-3">
    <%= f.label :project_id, 'Project' %>
    <%= f.select(:project_id, 
                 options_from_collection_for_select(Project.all, :id, :name, @ticket.project_id), {},
                 class: 'form-control') %>
  </div>
  <div class="form-group mt-lg-3">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group mt-lg-3">
    <%= f.label :body, 'Body' %>
    <%= f.text_area :body, class: 'form-control', rows: '5' %>
  </div>
  <div class="form-group mt-lg-3">
    <%= f.label :status, 'Status' %>
    <%= f.select :status,
                 options_for_select(Ticket::OPTIONS.map { |option| [option, option.downcase.split.join('_')]}, @ticket.status), {},
                 class: 'form_control' %>
  </div>
  <div class="form-group mt-lg-3">
    <%= f.label :assignee_id, 'Assignee' %>
    <%= f.select :assignee_id, 
                 options_from_collection_for_select(User.all, :id, :name, @ticket.assignee_id), {},
                 include_blank: 'No one',
                 class: 'form-control' %>
  </div>
  <div class="form-group mt-lg-3">
    <%= f.label :tag_ids, 'Tags' %>
    <%= f.select :tag_ids,
                 options_from_collection_for_select(Tag.order("LOWER(name)"), :id, :name, @ticket.tag_ids), {},  
                 class: 'form-control',
                 multiple: true %>
  </div>

  <%= f.submit(@ticket.new_record? ? 'Create Ticket' : 'Update Ticket', class: 'btn btn-primary btn-lg')%>
<% end %>

app/views/tickets/edit.html.erb
<%= render 'shared/nav' %>

<div class="container">
  <%= render 'shared/header', title: 'Editing Ticket' %>

  <%= render 'shared/errors', obj: @ticket %>

  <%= render 'form'%>
<div>

app/views/tickets/index.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: 'Tickets' %>

  <% if flash[:error].present? %>
    <p class="alert alert-danger"><%= flash[:error] %></p>
  <% end %>
  <% if flash[:success].present? %>
    <p class="alert alert-success"><%= flash[:success] %></p>
  <% end %>

  <%= form_tag tickets_path, method: :get, class: 'form-inline my-lg-3' do %>
    <span>Show tickets from</span>
    <%= select_tag 'ticket[project_id]', 
                  options_from_collection_for_select(Project.all, :id, :name, @project_id), 
                  include_blank: 'All Projects',
                  class: 'form-control ml-lg-3' %>
    <span class="ml-lg-3">with status</span>
    <%= select_tag 'ticket[status]', 
                  options_for_select(Ticket::OPTIONS.map { |option| [option, option.downcase.split.join('_')]}, @status), 
                  include_blank: 'Any Status',
                  class: 'form-control ml-lg-3' %>
    <span class="ml-lg-3">tagged</span>
    <%= select_tag 'tag_id', 
                  options_from_collection_for_select(Tag.order("LOWER(name)"), :id, :name, @tag),
                  include_blank: '-',
                  class: 'form-control ml-lg-3' %>
    <%= button_tag 'Update', class: 'btn btn-primary mx-lg-3' %>
    <%= link_to 'Clear', tickets_path %>
  <% end %>

  <% if @tickets.any? %>
    <%= render 'shared/ticket_list'%>
  <% else %>
    <p> No tickets matching the criteria. <%= link_to 'Clear filters and show all tickets', tickets_path %></p>
  <% end %>

  <button class='btn btn-outline-primary'><%= link_to 'New Ticket', new_ticket_path, class: 'boring' %></button>

</div>

app/views/tickets/new.html.erb
<%= render 'shared/nav' %>

<div class="container">
  <%= render 'shared/header', title: 'New Ticket' %>

  <%= render 'shared/errors', obj: @ticket %>
  
  <%= render 'form' %>

<div>

app/views/tickets/show.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/header', title: @ticket.name %>
  <p class="lead"><%= @ticket.body %></p>
  <p><strong>Tags:</strong> <%= @ticket.tags.to_a.map {|tag| tag.name }.join(', ') %></p>

  <%= link_to 'Edit', edit_ticket_path(@ticket.id) %>

  <table class="table w-100 table-hover table-sm mt-lg-3">
    <thead class="thead-dark">
      <tr>
        <th>Status</th>
        <th>Creator</th>
        <th>Assignee</th>
      <tr>
    </thead>
    <tr>
      <td><%= @ticket.status.capitalize.split('_').join(' ') %></td>
      <td><%= @ticket.creator.name %></td>
      <td><%= @ticket.assignee && @ticket.assignee.name %>
    </tr>
  </table>

  <h2>Comments</h1>

  <% if flash[:error].present? %>
    <p class="alert alert-danger"><%= flash[:error] %></p>
  <% end %>
  <% if flash[:success].present? %>
    <p class="alert alert-success"><%= flash[:success] %></p>
  <% end %>

  <% if @ticket.comments.any? %>
    <% @ticket.comments.each do |comment| %>
      <div class="card mb-lg-3">
        <div class="card-body">
          <p class="card-text"><%= comment.body %></p>
          <footer class="blockquote-footer">posted by <%= comment.creator.name %></footer>
          <%= link_to 'Edit', edit_ticket_comment_path(@ticket, comment) %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>There are no comments.</p>
  <% end %>

  <%= render 'shared/comment_form' %>
</div>

app/views/users/new.html.erb
<%= render 'shared/nav'%>

<div class="container">
  <%= render 'shared/errors', obj: @user%>

  <%= form_for @user do |f| %>
    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit "Register", class: 'btn btn-primary btn-lg'%>
  <% end %> 
</div>